### ISSUE TITLE
how do i get the PIN

### ISSUE THREAD

**Issue by Adam-B0mb** [UniversalDevicesInc-PG3/udi-poly-ecobee#9]
I had my polisy go out on me and had to reinstall the Ecobee node server.  it would not connect. trying to start from scratch.  I deleted the node server.  How do i get it to generate the PIN again so i can generate a new key?

**Comment by jimboca** [comment]
Check then nodeserver log to see if it shows the PIN or any errors.

**Comment by Adam-B0mb** [comment]
No Pin in the log.. here is what I am getting:
2023-10-09 07:18:55,624 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2023-10-09 07:18:55,632 MainThread udi_interface      INFO     __init__:<module>: UDI interface initializing
2023-10-09 07:18:55,633 MainThread udi_interface      INFO     __init__:<module>: User=polyglot
2023-10-09 07:18:55,634 MainThread udi_interface      INFO     __init__:<module>: Home=/var/polyglot
2023-10-09 07:18:55,635 MainThread udi_interface      INFO     __init__:<module>: Node Server Path=/var/polyglot/pg3/ns/000db959411c_3
2023-10-09 07:18:55,635 MainThread udi_interface      INFO     __init__:<module>: PG3INIT=eyJ1dWlkIjoiMDA6MGQ6Yjk6NTk6NDE6MWMiLCJwcm9maWxlTnVtIjozLCJsb2dMZXZlbCI6IldBUk5JTkciLCJ0b2tlbiI6IipsYnJ3Klp6VFIxM3VMeEwiLCJtcXR0SG9zdCI6ImxvY2FsaG9zdCIsIm1xdHRQb3J0IjoxODg4LCJzZWN1cmUiOjEsImlzUEczeCI6ZmFsc2UsInBnM1ZlcnNpb24iOiIzLjEuMjMiLCJpc3lWZXJzaW9uIjoiNS41LjkiLCJlZGl0aW9uIjoiU3RhbmRhcmQifQ==
2023-10-09 07:18:55,636 MainThread udi_interface      INFO     __init__:<module>: Loading interface module
2023-10-09 07:18:56,406 MainThread udi_interface      INFO     interface:<module>: Loading MQTT module
2023-10-09 07:18:56,957 MainThread udi_interface      INFO     interface:<module>: MQTT module loaded
2023-10-09 07:19:03,196 MainThread udi_interface      INFO     __init__:<module>: Loading udi_interface module
2023-10-09 07:19:03,219 MainThread udi_interface      INFO     __init__:<module>: Loading node module
2023-10-09 07:19:03,220 MainThread udi_interface      INFO     __init__:<module>: Loading custom module
2023-10-09 07:19:03,221 MainThread udi_interface      INFO     __init__:<module>: Loading isy module
2023-10-09 07:19:03,222 MainThread udi_interface      INFO     __init__:<module>: UDI interface initialized
2023-10-09 07:19:03,222 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.2.2 Starting...
2023-10-09 07:19:03,263 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2023-10-09 07:19:03,265 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db959411c_3/./ecobee-poly.py", line 7, in <module>
2023-10-09 07:19:03,266 MainThread udi_interface      ERROR    udi_interface:write: from nodes import VERSION,Controller
2023-10-09 07:19:03,267 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db959411c_3/nodes/__init__.py", line 1
2023-10-09 07:19:03,268 MainThread udi_interface      ERROR    udi_interface:write: er import Controller
2023-10-09 07:19:03,269 MainThread udi_interface      ERROR    udi_interface:write: ^
2023-10-09 07:19:03,270 MainThread udi_interface      ERROR    udi_interface:write: SyntaxError
2023-10-09 07:19:03,271 MainThread udi_interface      ERROR    udi_interface:write: :
2023-10-09 07:19:03,271 MainThread udi_interface      ERROR    udi_interface:write: invalid syntax

**Comment by jimboca** [comment]
Looks like you are still on PG3, please upgrade to PG3x.

**Comment by Adam-B0mb** [comment]
Hmmm. Was on PG3x.  I must have restored from an old backup(?).  Thanks!!

**Comment by jimboca** [comment]
Ok, it could be, but I can't be sure. Errors like that usually only happen in PG3. Please download log package and email to jimbo.automates@gmail.com

**Comment by jimboca** [comment]
Yes, you are using PG3, not PG3x:
`10/9/2023, 07:18:40 [pg3] info: Starting PG3 version 3.1.23
`

**Comment by Adam-B0mb** [comment]
Thanks again!!  Sorry to have bothered you.
Adam
